[package]
name = "CANNEDBI"
version = "0.0.2"
upgrade_policy = "compatible"

[dependencies]
# AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
# AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token", rev = "main" }

#AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "devnet" }
#AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token", rev = "devnet" }

AptosFramework = { local = "../../../aptos-core/aptos-move/framework/aptos-framework/"}
AptosToken = { local = "../../../aptos-core/aptos-move/framework/aptos-token/"}

[addresses]
can_coin = "_"
cannedbi_nft = "_"
#cannedbi = "_"
#deployer = "_"
# change it to `source_addr = "_" when calling `create-resource-account-and-publish-package` from the cli
#source_addr = "_"

# change it to the actual source address when publishing the module
#source_addr = "0xcafe"
# change it to the actual admin address when publishing the module
admin_addr = "_"