[package]
name = "CANNEDBI NFT"
version = "0.0.1"
upgrade_policy = "compatible"

[dependencies]
# AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "main" }
# AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token", rev = "main" }

# AptosFramework = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-framework", rev = "devnet" }
# AptosToken = { git = "https://github.com/aptos-labs/aptos-core.git", subdir = "aptos-move/framework/aptos-token", rev = "devnet" }

AptosFramework = { local = "../../../aptos-core/aptos-move/framework/aptos-framework/"}
AptosToken = { local = "../../../aptos-core/aptos-move/framework/aptos-token/"}




[addresses]
cannedbi_nft = "_"
deployer = "_"

